import * as React from "react";
import Avatar from "@mui/joy/Avatar";
import Chip from "@mui/joy/Chip";
import Box from "@mui/joy/Box";
import Button from "@mui/joy/Button";
import ButtonGroup from "@mui/joy/ButtonGroup";
import Card from "@mui/joy/Card";
import CardContent from "@mui/joy/CardContent";
import CardOverflow from "@mui/joy/CardOverflow";
import CardActions from "@mui/joy/CardActions";
import IconButton from "@mui/joy/IconButton";
import Typography from "@mui/joy/Typography";
import SvgIcon from "@mui/joy/SvgIcon";
import LinkButton from "./LinkButton";

export default function BioCard(props) {
  return (
    <Card
      sx={{
        // width: 320,
        maxWidth: "100%",
        boxShadow: "lg",
      }}
    >
      <CardContent sx={{ alignItems: "center", textAlign: "center" }}>
        <Avatar
          src={
            props.publisher.profilePicture?.path !== "autogenerated"
              ? `http://localhost:8080/medias/${props.publisher.profilePicture?.id}/files`
              : props.publisher.profilePicture?.fileName
          }
          sx={{ "--Avatar-size": "4rem" }}
        />
        <Chip
          size="sm"
          variant="solid"
          color={
            props.publisher.role == "ACADEMIC"
              ? "success"
              : props.publisher.role == "ORGANIZATION"
              ? "primary"
              : "warning"
          }
          sx={{
            mt: -1,
            mb: 1,
            border: "3px solid",
            borderColor: "background.surface",
          }}
        >
          {props.publisher.role.slice(0, 1).toUpperCase() +
            props.publisher.role.slice(1).toLowerCase()}
        </Chip>
        <Typography level="title-lg">
          {props.publisher.firstName} {props.publisher.lastName}{" "}
          {props.publisher.id}
        </Typography>
        <Typography level="body-sm" sx={{ maxWidth: "24ch" }}>
          {props.publisher.position} {props.publisher.type}
        </Typography>
        <Box
          sx={{
            display: "flex",
            gap: 2,
            mt: 2,
            "& > button": { borderRadius: "2rem" },
          }}
        ></Box>
      </CardContent>
      <CardOverflow sx={{ bgcolor: "background.level1" }}>
        <CardActions buttonFlex="1">
          <ButtonGroup
            variant="outlined"
            sx={{ bgcolor: "background.surface" }}
          >
            <LinkButton id={props.publisher.id} />
          </ButtonGroup>
        </CardActions>
      </CardOverflow>
    </Card>
  );
}
