import { useLocation } from "react-router-dom";
import "./ArticlePage.css";
import { Box, Typography, Container, Stack, Avatar } from "@mui/joy";

function getTimeDifference(dateString) {
    const date = new Date(dateString);
    const currentDate = new Date();
    const timeDifference = currentDate - date;
    const daysDifference = Math.floor(timeDifference / (1000 * 60 * 60 * 24));

    if (daysDifference === 0) {
        return "Today";
    } else if (daysDifference === 1) {
        return "Yesterday";
    } else {
        return `${daysDifference} Days Ago`;
    }
}
function ArticlePage() {
    let location = useLocation();
    console.log(location);

    return (
        <>
            <Container sx={{ maxWidth: "md", marginTop: 4 }}>
                <Typography
                    level="h1"
                    sx={{ fontWeight: "bold", textAlign: "center" }}
                >
                    {location.state.title}
                </Typography>
                <Stack
                    direction="row"
                    alignItems="center"
                    sx={{ mt: 2, justifyContent: "center" }}
                >
                    <Avatar
                        src={
                            location.state.publisher.profilePicture?.path !==
                            "autogenerated"
                                ? `http://localhost:8080/medias/${location.state.publisher.profilePicture?.id}/files`
                                : location.state.publisher.profilePicture
                                      ?.fileName
                        }
                        alt="Author"
                    />
                    <Box sx={{ ml: 2 }}>
                        <Typography level="body2" sx={{ fontWeight: "bold" }}>
                            {location.state.publisher.firstName +
                                " " +
                                location.state.publisher.lastName}
                        </Typography>
                        <Typography
                            level="body2"
                            sx={{ color: "text.secondary" }}
                        >
                            {getTimeDifference(location.state.createDateTime)}
                        </Typography>
                    </Box>
                </Stack>
                <Container
                    style={{
                        wordWrap: "break-word",
                        // marginTop: 2,
                        // display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        width: { xs: "100%", sm: "80%", md: "60%" },
                    }}
                >
                    <Typography
                        level="h4"
                        sx={{
                            mt: 2,
                            textAlign: "center",
                            color: "text.secondary",
                        }}
                    >
                        {location.state.brief}
                    </Typography>
                </Container>
                {location.state.medias.map((media) => {
                    <Box
                        component="img"
                        src={`http://localhost:8080/medias/${media.id}/files`}
                        alt="Article"
                        sx={{
                            width: "100%",
                            height: "300px",
                            objectFit: "cover",
                            borderRadius: 2,
                            boxShadow: 1,
                            mt: 4,
                        }}
                    />;
                })}
                <Container
                    sx={{
                        display: "flex",

                        justifyContent: "center",
                        wordWrap: "break-word",
                    }}
                >
                    <Typography
                        level="body1"
                        style={{
                            fontFamily: "Times New Roman , Times, serif",
                            fontSize: "1.2rem",
                            fontStyle: "oblique",
                            textAlign: "justify",
                            // whiteSpace: " nowrap",
                        }}
                        sx={{
                            mt: 4,
                            // lineHeight: 1.6,
                            maxWidth: { xs: "100%", sm: "80%", md: "60%" },
                        }}
                    >
                        {location.state.content}
                        {location.state.content}
                    </Typography>
                </Container>
            </Container>
        </>
    );
}
export default ArticlePage;
